### ISSUE TITLE
Android only?

### ISSUE THREAD

**Issue by EdLatorre** [yi-jiayu/whatsapp-spoilers#3]
At least not in iPhone

**Comment by yi-jiayu** [comment]
I'm not too sure about this actually. The "spoiler tag" is actually taking advantage of how the WhatsApp client handles long messages. On web and Android, it folds long messages behind the "Read more" button. However, it doesn't work in the conversation list view on Web, and behaviour could change anytime.

**Comment by yi-jiayu** [comment]
Closing in favour of #5
