### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gre4twh1te** [yi-jiayu/whatsapp-spoilers#4]
does not work on iOS - neither can you use the copy to clipboard button nor does it hide anything when you manually copy the generated text :/

**Comment by yi-jiayu** [comment]
Hello!

I don't have an iPhone, so I never tested it, but a previous issue (#3) also had to do with iOS. I'll see if I can borrow an iPhone to test.

It's possible that this trick doesn't work on all platforms, since it depends on undocumented behaviour in WhatsApp clients.

**Comment by yi-jiayu** [comment]
Opened a new issue to track iOS support and closing this: #5
