### ISSUE TITLE
Discrepancies between mobile and desktop 

### ISSUE THREAD

**Issue by LocalMoonman1125** [yi-jiayu/whatsapp-spoilers#6]
There seems to be differences between how it displays the 0 width spaces on desktop WhatsApp and mobile (android) WhatsApp.

I'm on android 8.1.0 on the latest public version of WhatsApp, and whilst the spoiler feature works on desktop when quoting a spoiler, on mobile, it displays without the spaces, just like as if you pressed on "read more." 
(mobile screenshot when quoting) 
![Screenshot_20191228-170148](https://user-images.githubusercontent.com/59314919/71546145-1a380900-2994-11ea-88bf-1cdc237ca7a7.png)

As of now the only way to mitigate this is by spamming a bunch of "spoilers" in the [] like so
![Screenshot_20191228-170132](https://user-images.githubusercontent.com/59314919/71546149-2328da80-2994-11ea-8d7d-05a5498b84e1.png)
, but by that point, this tool becomes very inelegant.

Do you think there is a fix for it?

**Comment by yi-jiayu** [comment]
You're right. It looks like adding three empty lines after the spoiler warning might help:

![Screenshot_20191229-001355](https://user-images.githubusercontent.com/11734309/71546302-7751b000-29d0-11ea-938e-7d36d1b916d7.png)

What do you think about this solution? It's not possible through the UI at the moment, but support could be added.

**Comment by LocalMoonman1125** [comment]
Yep, that seems like a much elegant fix for now. Thanks for the reply!

**Comment by yi-jiayu** [comment]
@LocalMoonman1125 Added an option to add some newlines between the spoiler warning and content, could you give it a try now?

**Comment by LocalMoonman1125** [comment]
![Screenshot_20191229-022452](https://user-images.githubusercontent.com/59314919/71551235-9bb68800-29e2-11ea-83bf-2fbca3690899.png)

**Comment by yi-jiayu** [comment]
👍
